### ISSUE TITLE
Match record suggestions

### ISSUE THREAD

**Issue by Chiuterence** [AndrewManHayChiu/court#30]
- No need for time (unnecessary, and the less inputs and simpler it is the better)
- instead of tickbox for doubles, have a button for "singles" or "boubles"
- "Match" to be changed to "Match details"
- "Sets" to be changed to "Result"
- Implement "edit" function in case a match is saved but the user wants to edit
- Implement ability for others to look up a match that was entered by someone else, or ensure that the other person can see the match result submitted by someone else, on their record, and then for that person to confirm or reject the record

**Tasks**
- [x] Convert doubles tickbox into match combination selection
- [x] Change title from 'Match' to Match details'
- [x] Change sub-title from 'Sets' to 'Results'
- [x] Implement feature to edit match details
    - [x] Create Django form
    - [x] Create Django view
 - [ ] #42

**Comment by AndrewManHayChiu** [comment]
Good suggestions

- [ ] Convert doubles tickbox into singles/doubles radial button
- [ ] Change title from 'Match' to Match details'
- [ ] Change sub-title from 'Sets' to 'Results'
- [ ] Implement feature to edit match details
    - [ ] Create Django form
    - [ ] Create Django view
 - [ ] Implement feature to confirm match details

**Comment by AndrewManHayChiu** [comment]
@Chiuterence 

For the doubles/singles suggestion, I'm thinking to change it to three options as radial buttons:

- singles
- doubles (default)
- mixed


Or should it be more granular, like:

- MS
- WS
- MD (default)
- WD
- XD

I'd like it to be able to be used for tournaments too, so the latter might be a preferable solution.

**Comment by AndrewManHayChiu** [comment]
Done all the tasks, except for 1 which is converted to a new issue.

Unlike the other issues, the outstanding one is not a must-have for an MVP.

Closing the issue now.
